00:00:00.002362 main     VirtualBox COM Server 6.1.34 r150636 win.amd64 (Mar 23 2022 00:36:21) release log
00:00:00.002364 main     Log opened 2022-07-28T19:22:22.732066100Z
00:00:00.002364 main     Build Type: release
00:00:00.002369 main     OS Product: Windows 11
00:00:00.002370 main     OS Release: 10.0.22000
00:00:00.002371 main     OS Service Pack: 
00:00:00.030039 main     DMI Product Name: Inspiron 3501
00:00:00.042902 main     DMI Product Version: 
00:00:00.042917 main     Firmware type: UEFI
00:00:00.043448 main     Secure Boot: VERR_PRIVILEGE_NOT_HELD
00:00:00.043469 main     Host RAM: 7914MB (7.7GB) total, 749MB available
00:00:00.043474 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
00:00:00.043475 main     Process ID: 18924
00:00:00.043476 main     Package type: WINDOWS_64BITS_GENERIC
00:00:00.123411          VirtualBox: object creation starts
00:00:00.123626          Home directory: 'C:\Users\Dell\.VirtualBox'
00:00:00.123775          Installed Drivers:
00:00:00.131906            C:\WINDOWS\system32\DRIVERS\VBoxNetLwf.sys (Version: 6.1.34.636)
00:00:00.132532            C:\WINDOWS\system32\DRIVERS\VBoxUSBMon.sys (Version: 6.1.34.636)
00:00:00.132787            C:\WINDOWS\system32\DRIVERS\VBoxSup.sys (Version: 6.1.34.636)
00:00:00.133495            C:\WINDOWS\System32\drivers\VBoxNetAdp6.sys (Version: 6.1.34.636)
00:00:00.147178          Loading settings file "C:\Users\Dell\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.150344          usbLibGetDevices: Starting USB device enumeration
00:00:00.170628          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 6
00:00:00.170809          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
00:00:00.172877          usbLibGetDevices: Found 2 USB devices, 0 captured
00:00:00.172915          USB: Unknown USB device detected (idVendor: 0x0c45, idProduct: 0x671e)
00:00:00.172945          USB: Unknown USB device detected (idVendor: 0x8087, idProduct: 0x0aaa)
00:00:00.314496          netIfIsWireless: CreateFile on '\\.\{2F54F43E-3696-498C-B582-D2DCFC9A4AF0}' failed with rcWin=2 (0x2) - ignoring
00:00:00.319344          HostDnsMonitor: initializing
00:00:00.327466          HostDnsMonitor: updating information
00:00:00.327491          HostDnsMonitor: old information
00:00:00.327491            no server entries
00:00:00.327492            no domain set
00:00:00.327493            no search string entries
00:00:00.327493          HostDnsMonitor: new information
00:00:00.327493            server 1: 10.0.0.80
00:00:00.327494            domain: phub.net.cable.rogers.com
00:00:00.327494            no search string entries
00:00:00.381204          VD: VDInit finished with VINF_SUCCESS
00:00:00.391955          Loading settings file "C:\Users\Dell\VirtualBox VMs\Fedora\Fedora.vbox" with version "1.16-windows"
00:00:00.392969          VirtualBox: object created
00:06:04.887157 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:06:04.903190 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 6
00:06:04.903368 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
00:06:04.903716 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
01:49:25.099194 USBPROXY usbLibGetDevices: Starting USB device enumeration
01:49:25.104534 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
01:49:25.106932 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
01:50:10.268869 USBPROXY usbLibGetDevices: Starting USB device enumeration
01:50:10.290133 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 6
01:50:10.290302 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
01:50:10.290743 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
01:53:36.779569 USBPROXY usbLibGetDevices: Starting USB device enumeration
01:53:36.783541 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
01:53:36.784012 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
01:57:48.508851 USBPROXY usbLibGetDevices: Starting USB device enumeration
01:57:48.541488 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 6
01:57:48.541681 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
01:57:48.542057 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
01:59:08.211963 USBPROXY usbLibGetDevices: Starting USB device enumeration
01:59:08.216071 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
01:59:08.216357 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
01:59:15.752919 USBPROXY usbLibGetDevices: Starting USB device enumeration
01:59:15.756564 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&c2333a7&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
01:59:15.756888 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
02:20:24.038950          Saving settings file "C:\Users\Dell\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
02:20:24.098953          Saving settings file "C:\Users\Dell\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
02:20:25.537410          Saving settings file "C:\Users\Dell\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
02:20:25.541481          Saving settings file "C:\Users\Dell\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
02:20:31.067963 main     VirtualBox: object deletion starts
02:20:31.068669 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\Dell\VirtualBox VMs\Fedora\Fedora.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
02:20:31.072865 main     HostDnsMonitor: shutting down ...
02:20:31.073081 main     HostDnsMonitor: shut down
02:20:31.074948 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={d0a0163f-e254-4e5b-a1f2-011cf991c38d} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
02:20:31.075461 main     VirtualBox: object deleted
